name: Build-release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
    - '**'
    - '.github/workflows/Android-Action.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
